
SGE_CLUSTER_NAME="starcluster"
SGE_ROOT="/opt/sge6"
SGE_QMASTER_PORT="63231"
SGE_EXECD_PORT="63232"
SGE_ENABLE_SMF="false"
CELL_NAME="default"
ADMIN_USER=""
QMASTER_SPOOL_DIR="/opt/sge6/default/spool/qmaster"
EXECD_SPOOL_DIR="/opt/sge6/default/spool"
GID_RANGE="20000-20100"
SPOOLING_METHOD="classic"
DB_SPOOLING_SERVER="none"
DB_SPOOLING_DIR="/opt/sge6/default/spooldb"
PAR_EXECD_INST_COUNT="20"
ADMIN_HOST_LIST=" domU-12-31-38-06-B4-51.compute-1.internal ip-10-127-77-94.ec2.internal domU-12-31-38-04-92-71.compute-1.internal ip-10-126-210-206.ec2.internal ip-10-127-37-27.ec2.internal ip-10-125-83-89.ec2.internal ip-10-125-97-31.ec2.internal ip-10-127-39-35.ec2.internal ip-10-125-71-102.ec2.internal ip-10-127-55-19.ec2.internal domU-12-31-38-04-58-34.compute-1.internal ip-10-127-65-145.ec2.internal ip-10-127-23-227.ec2.internal domU-12-31-38-04-84-21.compute-1.internal ip-10-125-85-74.ec2.internal ip-10-126-203-73.ec2.internal ip-10-127-70-238.ec2.internal domU-12-31-38-00-F1-41.compute-1.internal ip-10-126-218-154.ec2.internal ip-10-126-223-180.ec2.internal domU-12-31-38-06-B8-61.compute-1.internal domU-12-31-38-04-92-47.compute-1.internal ip-10-125-71-10.ec2.internal ip-10-125-78-24.ec2.internal ip-10-126-109-192.ec2.internal"
SUBMIT_HOST_LIST=" domU-12-31-38-06-B4-51.compute-1.internal ip-10-127-77-94.ec2.internal domU-12-31-38-04-92-71.compute-1.internal ip-10-126-210-206.ec2.internal ip-10-127-37-27.ec2.internal ip-10-125-83-89.ec2.internal ip-10-125-97-31.ec2.internal ip-10-127-39-35.ec2.internal ip-10-125-71-102.ec2.internal ip-10-127-55-19.ec2.internal domU-12-31-38-04-58-34.compute-1.internal ip-10-127-65-145.ec2.internal ip-10-127-23-227.ec2.internal domU-12-31-38-04-84-21.compute-1.internal ip-10-125-85-74.ec2.internal ip-10-126-203-73.ec2.internal ip-10-127-70-238.ec2.internal domU-12-31-38-00-F1-41.compute-1.internal ip-10-126-218-154.ec2.internal ip-10-126-223-180.ec2.internal domU-12-31-38-06-B8-61.compute-1.internal domU-12-31-38-04-92-47.compute-1.internal ip-10-125-71-10.ec2.internal ip-10-125-78-24.ec2.internal ip-10-126-109-192.ec2.internal"
EXEC_HOST_LIST=" domU-12-31-38-06-B4-51.compute-1.internal ip-10-127-77-94.ec2.internal domU-12-31-38-04-92-71.compute-1.internal ip-10-126-210-206.ec2.internal ip-10-127-37-27.ec2.internal ip-10-125-83-89.ec2.internal ip-10-125-97-31.ec2.internal ip-10-127-39-35.ec2.internal ip-10-125-71-102.ec2.internal ip-10-127-55-19.ec2.internal domU-12-31-38-04-58-34.compute-1.internal ip-10-127-65-145.ec2.internal ip-10-127-23-227.ec2.internal domU-12-31-38-04-84-21.compute-1.internal ip-10-125-85-74.ec2.internal ip-10-126-203-73.ec2.internal ip-10-127-70-238.ec2.internal domU-12-31-38-00-F1-41.compute-1.internal ip-10-126-218-154.ec2.internal ip-10-126-223-180.ec2.internal domU-12-31-38-06-B8-61.compute-1.internal domU-12-31-38-04-92-47.compute-1.internal ip-10-125-71-10.ec2.internal ip-10-125-78-24.ec2.internal ip-10-126-109-192.ec2.internal"
EXECD_SPOOL_DIR_LOCAL="/opt/sge6/default/spool/exec_spool_local"
HOSTNAME_RESOLVING="true"
SHELL_NAME="ssh"
COPY_COMMAND="scp"
DEFAULT_DOMAIN="none"
ADMIN_MAIL="none@none.edu"
ADD_TO_RC="false"
SET_FILE_PERMS="true"
RESCHEDULE_JOBS="wait"
SCHEDD_CONF="1"
SHADOW_HOST=""
EXEC_HOST_LIST_RM=""
REMOVE_RC="true"
WINDOWS_SUPPORT="false"
WIN_ADMIN_NAME="Administrator"
WIN_DOMAIN_ACCESS="false"
CSP_RECREATE="false"
CSP_COPY_CERTS="false"
CSP_COUNTRY_CODE="US"
CSP_STATE="MA"
CSP_LOCATION="BOSTON"
CSP_ORGA="MIT"
CSP_ORGA_UNIT="OEIT"
CSP_MAIL_ADDRESS="none@none.edu"

